# Generated by Django 5.0.6 on 2026-09-18 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Category description')),
                ('image', models.URLField(blank=True, default='', help_text='Image URL for category', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'), models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=255)),
                ('slug', models.SlugField(help_text='Unique URL-friendly slug', max_length=255, unique=True)),
                ('brand', models.CharField(blank=True, db_index=True, default='', help_text='Product brand or manufacturer', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed product description')),
                ('ingredients', models.TextField(blank=True, default='', help_text='Supplement ingredients list')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base retail price', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted sale price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available inventory units')),
                ('image', models.URLField(blank=True, default='', help_text='Product image URL', max_length=500)),
                ('weight', models.CharField(blank=True, default='', help_text="Weight or size (e.g. '1kg', '60 servings')", max_length=50)),
                ('flavour', models.CharField(blank=True, default='', help_text="Flavour variant (e.g. 'Chocolate', 'Unflavoured')", max_length=100)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Structured specifications (nutritional facts, certifications, etc.)')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this product is active for sale')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured supplement flag for storefront highlight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_pr_slug_3edc0c_idx'), models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'), models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'), models.Index(fields=['is_active', 'is_featured'], name='products_pr_is_acti_2fee29_idx'), models.Index(fields=['category', 'is_active'], name='products_pr_categor_50f5f1_idx')],
            },
        ),
    ]
